#!/usr/bin/env bash


# validate strings that bash supports (no nul support)
validate-utf8() {
	local s=$1

	# 0xxxxxxx                            1 byte,  7 bits
	# 110xxxxx 10xxxxxx                   2 bytes, 11 bits
	# 1110xxxx 10xxxxxx 10xxxxxx          3 bytes, 16 bits
	# 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx 4 bytes, 21 bits

	local LC_ALL=C
	local len=${#s}

	local i=0
	while ((i < len)); do
		local cp b1 b2 b3 b4 n

		# grab first byte
		printf -v b1 '%d' "'${s:i:1}"

		# check: b is 0xxxxxxx (1 octet)
		if (( (b1 & 2#10000000) == 0 )); then
			# 1 byte character, ASCII
			n=1

			# 0xxxxxxx
			cp=$(( b1 & 2#01111111 ))

		# check: b is 110xxxxx (2 octet)
		elif (( (b1 & 2#11100000) == 2#11000000 )); then
			# 2 byte character
			n=2

			(( i + 1 < len )) || return 1

			printf -v b2 '%d' "'${s:i+1:1}"

			(( (b2 & 2#11000000) == 2#10000000 )) || return 1

			# 110xxxxx 10xxxxxx
			cp=$((
				((b1 & 2#00011111) << 6) |
				 (b2 & 2#00111111)
			))

		# check: b is 1110xxxx (3 octet)
		elif (( (b1 & 2#11110000) == 2#11100000 )); then
			# 3 byte character
			n=3

			(( i + 2 < len )) || return 1

			printf -v b2 '%d' "'${s:i+1:1}"
			printf -v b3 '%d' "'${s:i+2:1}"

			(( (b2 & 2#11000000) == 2#10000000 )) || return 1
			(( (b3 & 2#11000000) == 2#10000000 )) || return 1

			# 1110xxxx 10xxxxxx 10xxxxxx
			cp=$((
				((b1 & 2#00001111) << 12) |
				((b2 & 2#00111111) << 6) |
				 (b3 & 2#00111111)
			))

		# check: b is 11110xxx (4 octet)
		elif (( (b1 & 2#11111000) == 2#11110000 )); then
			# 4 byte character
			n=4

			(( i + 3 < len )) || return 1

			printf -v b2 '%d' "'${s:i+1:1}"
			printf -v b3 '%d' "'${s:i+2:1}"
			printf -v b4 '%d' "'${s:i+3:1}"

			(( (b2 & 2#11000000) == 2#10000000 )) || return 1
			(( (b3 & 2#11000000) == 2#10000000 )) || return 1
			(( (b4 & 2#11000000) == 2#10000000 )) || return 1

			# 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
			cp=$((
				((b1 & 2#00000111) << 18) |
				((b2 & 2#00111111) << 12) |
				((b3 & 2#00111111) << 6) |
				 (b4 & 2#00111111)
			))
		else
			return 1
		fi
		(( i += n ))

		# at this point we have a codepoint and we've filtered out
		# invalid "looking" bytes, but we still have more work to do

		# check for overlong sequences
		case "$n" in
			1) ((cp >= 0x00000000 && cp <= 0x0000007F)) || return 1;;
			2) ((cp >= 0x00000080 && cp <= 0x000007FF)) || return 1;;
			3) ((cp >= 0x00000800 && cp <= 0x0000FFFF)) || return 1;;
			4) ((cp >= 0x00010000 && cp <= 0x0010FFFF)) || return 1;;
			*) exit 1;;
		esac

		# check for utf-16 surrogate pair domain
		# U+D800 and U+DFFF
		((cp >= 0xd800 && cp <= 0xdff)) && return 1
	done

	return 0
}

strings=(
	'a'
	'hello'
	$'a\xffb'
	$'\xc2\xff' # 2 byte string: bad continuation marker
	$'\xc2\xa4' # 2 byte string: ¤
	$'\xe2\x9b\x84' # 3 byte string: ⛄
	$'\xf0\x9f\xa5\xb7' # 4 byte string: 🥷

	# overlong "!"
	# \x21
	# 00010101
	# 00010101 <- 1 byte !
	# 110xxxxx 10xxxxxx
	# 11000000 10010101 <- 2 byte !
	# 1100_0000_1001_0101
	#  12   0    9    5
	#    c0        95
	#    c0  95
	$'\xc0\x95'

	# utf-16 surrogate pairs
	# U+D800 and U+DFFF
	$'\xd8\x00'
	$'\xdf\xff'
	$'\xda\xff'
)

for s in "${strings[@]}"; do
	echo -n "testing: ${s@Q}... "

	if validate-utf8 "$s"; then
		echo $'\e[92mvalid\e[0m'
	else
		echo $'\e[91minvalid\e[0m'
	fi
done
